version: '3.8'

services:
  web:
    container_name: web
    build: .
    #command: python -m celery -A src.run_task worker -l INFO
    command: python main.py
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    depends_on:
      - redis
    restart: always
        

  redis:
    image: redis:latest
    container_name: redis
    env_file:
      - ./.env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis:/var/lib/redis/data

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - mongo:/data/db


volumes:
  redis:
  mongo: